### ISSUE TITLE
Error when attempting to run "exoplanetssyssim/src/setup.jl"

### ISSUE THREAD

**Issue by hematthi** [eford/ExoplanetsSysSim.jl#1]
In attempting to install the contents of ExoplanetSysSim and its non-standard packages using the following line,

> julia> include(joinpath(Pkg.dir(),"exoplanetssyssim/src/setup.jl"))

I get the following error:

> INFO: Cloning ABC from git@github.com:eford/ABC.jl.git
> INFO: Computing changes...
> INFO: Cloning cache of Distances from https://github.com/JuliaStats/Distances.jl.git
> INFO: Installing Distances v0.4.1
> INFO: Cloning CORBITS from git@github.com:jbrakensiek/CORBITS.git
> INFO: Computing changes...
> g++ -c -fPIC -Wall -O2 -I lib -I data -I stat lib/math_misc.cpp -o lib/math_misc.o
> g++ -c -fPIC -Wall -O2 -I lib -I data -I stat lib/point3D.cpp -o lib/point3D.o
> g++ -c -fPIC -Wall -O2 -I lib -I data -I stat lib/transit.cpp -o lib/transit.o
> lib/transit.cpp:292:23: error: variable length array of non-POD element type
>       'crossing'
>     crossing points[n][n];
>                       ^
> lib/transit.cpp:294:16: error: variable length array of non-POD element type
>       'vertex'
>     vertex hull[8 * n * n];
>                ^
> lib/transit.cpp:526:21: error: variable length array of non-POD element type
>       'planet_ellipse'
>     planet_ellipse p[n];
>                     ^
> lib/transit.cpp:545:21: error: variable length array of non-POD element type
>       'planet_ellipse'
>     planet_ellipse p[n];
>                     ^
> 4 errors generated.
> make: *** [lib/transit.o] Error 1
> ERROR: LoadError: failed process: Process(`make lib`, ProcessExited(2)) [2]
> Stacktrace:
>  [1] pipeline_error(::Base.Process) at ./process.jl:682
>  [2] run(::Cmd) at ./process.jl:651
>  [3] include_from_node1(::String) at ./loading.jl:569
>  [4] include(::String) at ./sysimg.jl:14
> while loading /Users/Matthias/.julia/v0.6/exoplanetssyssim/src/setup.jl, in expression starting on line 20

Note that my version of g++ appears to be the default one from Xcode:

> g++ --version
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 7.3.0 (clang-703.0.31)
> Target: x86_64-apple-darwin15.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by eford** [comment]
I've updated the setup script in an effort to fix the case issue and so that it still tries to install ABC and CORBITS, but only prints a warning message if there's a problem.  
I tested the new setup script on unix and it worked for me.  
If someone tests the new setup script on Windows or Macs, please let me know regardless of the outcome.

**Comment by hematthi** [comment]
I just cloned the entire repository to my Mac again, using: "Pkg.clone("git@github.com:hematthi/ExoplanetsSysSim.jl.git")" (I renamed my old .julia directory as a backup).

After trying the new setup script: "include(joinpath(Pkg.dir("ExoplanetsSysSim"),"src/setup.jl"))", unfortunately I seem to get the exact same error message as before:

> INFO: Cloning ABC from git@github.com:eford/ABC.jl.git
INFO: Computing changes...
INFO: Cloning cache of Distances from https://github.com/JuliaStats/Distances.jl.git
INFO: Cloning cache of MultivariateStats from https://github.com/JuliaStats/MultivariateStats.jl.git
INFO: Installing Distances v0.5.0
INFO: Installing MultivariateStats v0.4.0
INFO: Building SpecialFunctions
INFO: Cloning CORBITS from git@github.com:jbrakensiek/CORBITS.git
INFO: Computing changes...
g++ -c -fPIC -Wall -O2 -I lib -I data -I stat lib/math_misc.cpp -o lib/math_misc.o
g++ -c -fPIC -Wall -O2 -I lib -I data -I stat lib/point3D.cpp -o lib/point3D.o
g++ -c -fPIC -Wall -O2 -I lib -I data -I stat lib/transit.cpp -o lib/transit.o
lib/transit.cpp:292:23: error: variable length array of non-POD element type
      'crossing'
    crossing points[n][n];
                      ^
lib/transit.cpp:294:16: error: variable length array of non-POD element type
      'vertex'
    vertex hull[8 * n * n];
               ^
lib/transit.cpp:526:21: error: variable length array of non-POD element type
      'planet_ellipse'
    planet_ellipse p[n];
                    ^
lib/transit.cpp:545:21: error: variable length array of non-POD element type
      'planet_ellipse'
    planet_ellipse p[n];
                    ^
4 errors generated.
make: *** [lib/transit.o] Error 1
ERROR: LoadError: failed process: Process(`make lib`, ProcessExited(2)) [2]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
while loading /Users/Matthias/.julia/v0.6/ExoplanetsSysSim/src/setup.jl, in expression starting on line 19

I can't quite remember what we did to get around this last time (or whether we did anything at all)?

**Comment by eford** [comment]
I think last time, we just ignored it since you weren't using CORBITS.  But we should fix this.  Really, it's an issue with https://github.com/jbrakensiek/CORBITS rather than this project.  I've tried adding some const's in my fork of CORBITS to see if that's enough to fix it.  
https://github.com/eford/CORBITS/commit/9ac2e42414c40dbbc8ebaa04b48930ebd1df01cf
Could you report back on if that eliminates the error messages?

**Comment by hematthi** [comment]
OK, now I just get the warnings instead of the error messages:

> julia> include(joinpath(Pkg.dir("ExoplanetsSysSim"),"src/setup.jl"))
INFO: Cloning ABC from git@github.com:eford/ABC.jl.git
WARNING: Attempted to install ABC.jl package, but was not successful.
WARNING: While most of SysSim will still work, some functionality will not be avaliable unless you install CORBITS correctly.
INFO: Cloning CORBITSa from git@github.com:jbrakensiek/CORBITSa.git
WARNING: Attempted to install CORBITS.jl package, but was not successful.
WARNING: While most of SysSim will still work, some functionality will not be avaliable unless you install CORBITS correctly.
